### ISSUE TITLE
tests are failing

### ISSUE THREAD

**Issue by ignatenkobrain** [kislyuk/argcomplete#174]
```python
======================================================================
ERROR: test_file_completion (test.test.TestArgcomplete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 252, in test_file_completion
    os.makedirs(os.path.join("abcdefж", "klm"))
  File "/usr/lib64/python2.7/os.py", line 148, in makedirs
    if head and tail and not path.exists(head):
  File "/usr/lib64/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0436' in position 6: ordinal not in range(128)

======================================================================
ERROR: test_filescompleter_filetype_integration (test.test.TestArgcomplete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 267, in test_filescompleter_filetype_integration
    os.makedirs(os.path.join("abcdefж", "klm"))
  File "/usr/lib64/python2.7/os.py", line 148, in makedirs
    if head and tail and not path.exists(head):
  File "/usr/lib64/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0436' in position 6: ordinal not in range(128)

======================================================================
ERROR: test_non_ascii (test.test.TestArgcomplete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 354, in test_non_ascii
    self.assertEqual(set(self.run_completer(make_parser(), cmd)),
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 339, in make_parser
    parser.add_argument(_str("--книга"), choices=[
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/argcomplete/compat.py", line 18, in ensure_bytes
    x = x.encode(encoding)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-6: ordinal not in range(128)

======================================================================
ERROR: test_double_quoted_completion (test.test.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 809, in test_double_quoted_completion
    self.assertEqual(self.sh.run_command('prog basic "f\t'), 'foo\r\n')
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 914, in run_command
    self.child.expect_exact('###', timeout=1)
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 390, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f38a73602d0>
command: /usr/bin/tcsh
args: ['/usr/bin/tcsh']
buffer (last 100 chars): u'\\#\\#\\ \x08#\r\r\nUnmatched \'"\'.\r\n\x1b]0;brain@x1carbon:argcomplete-1.7.0\x07[brain@x1carbon argcomplete-1.7.0]$ '
before (last 100 chars): u'\\#\\#\\ \x08#\r\r\nUnmatched \'"\'.\r\n\x1b]0;brain@x1carbon:argcomplete-1.7.0\x07[brain@x1carbon argcomplete-1.7.0]$ '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 32286
child_fd: 23
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "###"

======================================================================
ERROR: test_quoted_exact (test.test.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 826, in test_quoted_exact
    self.assertEqual(self.sh.run_command('prog basic "f\t--'), 'foo\r\n')
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 914, in run_command
    self.child.expect_exact('###', timeout=1)
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 390, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f38a7366110>
command: /usr/bin/tcsh
args: ['/usr/bin/tcsh']
buffer (last 100 chars): u'\\#\\ \x08#\\#\r\r\nUnmatched \'"\'.\r\n\x1b]0;brain@x1carbon:argcomplete-1.7.0\x07[brain@x1carbon argcomplete-1.7.0]$ '
before (last 100 chars): u'\\#\\ \x08#\\#\r\r\nUnmatched \'"\'.\r\n\x1b]0;brain@x1carbon:argcomplete-1.7.0\x07[brain@x1carbon argcomplete-1.7.0]$ '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 32423
child_fd: 28
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "###"

======================================================================
ERROR: test_single_quoted_completion (test.test.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 806, in test_single_quoted_completion
    self.assertEqual(self.sh.run_command("prog basic 'f\t"), 'foo\r\n')
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 914, in run_command
    self.child.expect_exact('###', timeout=1)
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 390, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f38a7366810>
command: /usr/bin/tcsh
args: ['/usr/bin/tcsh']
buffer (last 100 chars): u"\\#\\#\\ \x08#\r\r\nUnmatched '''.\r\n\x1b]0;brain@x1carbon:argcomplete-1.7.0\x07[brain@x1carbon argcomplete-1.7.0]$ "
before (last 100 chars): u"\\#\\#\\ \x08#\r\r\nUnmatched '''.\r\n\x1b]0;brain@x1carbon:argcomplete-1.7.0\x07[brain@x1carbon argcomplete-1.7.0]$ "
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 32505
child_fd: 31
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "###"

======================================================================
ERROR: test_single_quotes_in_double_quotes (test.test.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 860, in test_single_quotes_in_double_quotes
    self.assertEqual(self.sh.run_command('prog quote "1\t'), "1'1\r\n")
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 914, in run_command
    self.child.expect_exact('###', timeout=1)
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 390, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f38a7366a90>
command: /usr/bin/tcsh
args: ['/usr/bin/tcsh']
buffer (last 100 chars): u'\\#\\#\\ \x08#\r\r\nUnmatched \'"\'.\r\n\x1b]0;brain@x1carbon:argcomplete-1.7.0\x07[brain@x1carbon argcomplete-1.7.0]$ '
before (last 100 chars): u'\\#\\#\\ \x08#\r\r\nUnmatched \'"\'.\r\n\x1b]0;brain@x1carbon:argcomplete-1.7.0\x07[brain@x1carbon argcomplete-1.7.0]$ '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 32532
child_fd: 32
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "###"

======================================================================
ERROR: test_single_quotes_in_single_quotes (test.test.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 865, in test_single_quotes_in_single_quotes
    self.assertEqual(self.sh.run_command("prog quote '1\t"), "1'1\r\n")
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 914, in run_command
    self.child.expect_exact('###', timeout=1)
  File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 390, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f38a7366cd0>
command: /usr/bin/tcsh
args: ['/usr/bin/tcsh']
buffer (last 100 chars): u"\\#\\#\\ \x08#\r\r\nUnmatched '''.\r\n\x1b]0;brain@x1carbon:argcomplete-1.7.0\x07[brain@x1carbon argcomplete-1.7.0]$ "
before (last 100 chars): u"\\#\\#\\ \x08#\r\r\nUnmatched '''.\r\n\x1b]0;brain@x1carbon:argcomplete-1.7.0\x07[brain@x1carbon argcomplete-1.7.0]$ "
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 32559
child_fd: 33
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "###"

======================================================================
FAIL: test_continuation (test.test.TestBash)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 821, in test_continuation
    self.assertEqual(self.sh.run_command('prog cont f\t--'), 'foo=--\r\n')
AssertionError: u'f--\r\n' != u'foo=--\r\n'
- f--
+ foo=--
?  +++


======================================================================
FAIL: test_partial_completion (test.test.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 803, in test_partial_completion
    self.assertEqual(self.sh.run_command('prog basic b\tr'), 'bar\r\n')
AssertionError: u"usage: prog basic [-h] {foo,bar,baz}\r\nprog basic: error: argument arg: inval [truncated]... != u'bar\r\n'
+ bar
- usage: prog basic [-h] {foo,bar,baz}
- prog basic: error: argument arg: invalid choice: 'build/r' (choose from 'foo', 'bar', 'baz')


======================================================================
FAIL: test_simple_completion (test.test.TestTcsh)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-argcomplete/argcomplete-1.7.0/test/test.py", line 800, in test_simple_completion
    self.assertEqual(self.sh.run_command('prog basic f\t'), 'foo\r\n')
AssertionError: u"usage: prog basic [-h] {foo,bar,baz}\r\nprog basic: error: argument arg: inval [truncated]... != u'foo\r\n'
+ foo
- usage: prog basic [-h] {foo,bar,baz}
- prog basic: error: argument arg: invalid choice: 'f' (choose from 'foo', 'bar', 'baz')


----------------------------------------------------------------------
```

**Comment by ignatenkobrain** [comment]
for first 2, it looks like I have to set LC_ALL to some UTF-8 locale..

**Comment by evanunderscore** [comment]
For the encoding errors, `locale.getpreferredencoding()` seems to be returning `ascii` for you. The tcsh errors are somewhat fragile, so I'm not entirely surprised about those. The bash error worries me and looks like the same one @kislyuk saw in #160.

Can you post versions of everything you're using? Mostly bash and tcsh, plus your locale settings. Unless I can reproduce these errors, I probably can't be of much help.

**Comment by ignatenkobrain** [comment]
* python-2.7.12-8.fc26.x86_64
* python2-pexpect-4.1.0-3.fc26.noarch
* bash-4.3.43-4.fc26.x86_64

```
export CONFIG_SITE="NONE"
export HISTCONTROL="ignoredups"
export HISTSIZE="1000"
export HOME="/builddir"
export HOSTNAME=""
export LANG="C"
export LC_ALL="C.UTF-8"
export LOGNAME="mockbuild"
export MAIL="/var/spool/mail/mockbuild"
export OLDPWD="/builddir/build/BUILD"
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/builddir/.local/bin:/builddir/bin"
export PKG_CONFIG_PATH=":/usr/lib64/pkgconfig:/usr/share/pkgconfig"
export PROMPT_COMMAND="printf \"\\033]0;<mock-chroot>\\007\""
export PWD="/builddir/build/BUILD/argcomplete-1.7.0"
export RPM_ARCH="x86_64"
export RPM_BUILD_DIR="/builddir/build/BUILD"
export RPM_BUILD_ROOT="/builddir/build/BUILDROOT/python-argcomplete-1.7.0-1.fc26.x86_64"
export RPM_DOC_DIR="/usr/share/doc"
export RPM_LD_FLAGS="-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld"
export RPM_OPT_FLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic"
export RPM_OS="linux"
export RPM_PACKAGE_NAME="python-argcomplete"
export RPM_PACKAGE_RELEASE="1.fc26"
export RPM_PACKAGE_VERSION="1.7.0"
export RPM_SOURCE_DIR="/builddir/build/SOURCES"
export SHELL="/bin/bash"
export SHLVL="2"
export TERM="vt100"
export USER="mockbuild"
```

Same happens with python3.

**Comment by evanunderscore** [comment]
Are you sure `C.UTF-8` is supported on your distro? I get this:

```
$ export LC_ALL='C.UTF-8'
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
```

Which then gives me the three encoding-related errors you're seeing.

**Comment by kislyuk** [comment]
@evanunderscore, I've disabled the tcsh tests until we can work out what happened with them.

As for the bash tests, I can't reproduce all of the errors in @ignatenkobrain's log but here is what I get. I checked out the last release, v1.7.0, and there are no test failures there (aside from tcsh), so we'll need to bisect the commits since then.
```
kislyuk@serenity:~/projects/argcomplete>make test
./setup.py flake8
running flake8
python test/test.py -v
test_action_activation (__main__.TestArgcomplete) ... ok
test_action_activation_with_subparser (__main__.TestArgcomplete) ... ok
test_append_space (__main__.TestArgcomplete) ... ok
test_basic_completion (__main__.TestArgcomplete) ... ok
test_choices (__main__.TestArgcomplete) ... ok
test_completers (__main__.TestArgcomplete) ... ok
test_custom_validator (__main__.TestArgcomplete) ... ok
test_different_validators (__main__.TestArgcomplete) ... ok
test_directory_completion (__main__.TestArgcomplete) ... ok
test_display_completions (__main__.TestArgcomplete) ... ok
test_exclusive (__main__.TestArgcomplete) ... ok
test_exclusive_class (__main__.TestArgcomplete) ... ok
test_file_completion (__main__.TestArgcomplete) ... ok
test_filescompleter_filetype_integration (__main__.TestArgcomplete) ... ok
test_mixed_optional_positional (__main__.TestArgcomplete) ... ok
test_nargs_one_or_more (__main__.TestArgcomplete) ... ok
test_nargs_optional (__main__.TestArgcomplete) ... ok
test_nargs_zero_or_more (__main__.TestArgcomplete) ... ok
test_non_ascii (__main__.TestArgcomplete) ... ok
test_non_str_choices (__main__.TestArgcomplete) ... ok
test_optional_long_short_filtering (__main__.TestArgcomplete) ... ok
test_optional_nargs (__main__.TestArgcomplete) ... ok
test_positional_remainder (__main__.TestArgcomplete) ... ok
test_readline_entry_point (__main__.TestArgcomplete) ... ok
test_skipped_completer (__main__.TestArgcomplete) ... ok
test_subparser_completers (__main__.TestArgcomplete) ... ok
test_subparsers (__main__.TestArgcomplete) ... ok
test_suppress_args (__main__.TestArgcomplete) ... ok
test_repl_multiple_complete (__main__.TestArgcompleteREPL) ... ok
test_repl_parse_after_complete (__main__.TestArgcompleteREPL) ... usage: test.py [-h] --foo FOO {bar}
test.py: error: too few arguments
usage: test.py [-h] --foo FOO {bar}
test.py: error: argument --foo is required
ok
test_repl_reuse_parser_with_positional (__main__.TestArgcompleteREPL) ... ok
test_repl_subcommand (__main__.TestArgcompleteREPL) ... ok
test_repl_subparser_parse_after_complete (__main__.TestArgcompleteREPL) ... usage: test.py foo [-h] {bar}
test.py foo: error: too few arguments
ok
test_continuation (__main__.TestBash) ... ok
test_double_quoted_completion (__main__.TestBash) ... ok
test_exclamation_in_double_quotes (__main__.TestBash) ... expected failure
test_parse_special_characters (__main__.TestBash) ... ok
test_parse_special_characters_dollar (__main__.TestBash) ... expected failure
test_partial_completion (__main__.TestBash) ... ok
test_quoted_exact (__main__.TestBash) ... FAIL
test_quoted_space (__main__.TestBash) ... ok
test_simple_completion (__main__.TestBash) ... ok
test_single_quoted_completion (__main__.TestBash) ... ok
test_single_quotes_in_double_quotes (__main__.TestBash) ... ok
test_single_quotes_in_single_quotes (__main__.TestBash) ... expected failure
test_special_characters (__main__.TestBash) ... ok
test_special_characters_double_quoted (__main__.TestBash) ... ok
test_special_characters_single_quoted (__main__.TestBash) ... ok
test_unquoted_space (__main__.TestBash) ... ok
test_continuation (__main__.TestBashGlobal) ... FAIL
test_double_quoted_completion (__main__.TestBashGlobal) ... ok
test_exclamation_in_double_quotes (__main__.TestBashGlobal) ... expected failure
test_parse_special_characters (__main__.TestBashGlobal) ... ok
test_parse_special_characters_dollar (__main__.TestBashGlobal) ... expected failure
test_partial_completion (__main__.TestBashGlobal) ... ok
test_quoted_exact (__main__.TestBashGlobal) ... FAIL
test_quoted_space (__main__.TestBashGlobal) ... ok
test_simple_completion (__main__.TestBashGlobal) ... ok
test_single_quoted_completion (__main__.TestBashGlobal) ... ok
test_single_quotes_in_double_quotes (__main__.TestBashGlobal) ... ok
test_single_quotes_in_single_quotes (__main__.TestBashGlobal) ... expected failure
test_special_characters (__main__.TestBashGlobal) ... ok
test_special_characters_double_quoted (__main__.TestBashGlobal) ... ok
test_special_characters_single_quoted (__main__.TestBashGlobal) ... ok
test_unquoted_space (__main__.TestBashGlobal) ... ok
test_escaped_special (__main__.TestSplitLine) ... ok
test_escaped_special_in_double_quotes (__main__.TestSplitLine) ... expected failure
test_simple (__main__.TestSplitLine) ... ok
test_unescaped_special (__main__.TestSplitLine) ... expected failure

======================================================================
FAIL: test_quoted_exact (__main__.TestBash)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 856, in test_quoted_exact
    self.assertEqual(self.sh.run_command('prog basic "f\t--'), 'foo\r\n')
AssertionError: u"usage: prog basic [-h] {foo,bar,baz}\r\nprog basic: error: argument arg: inval [truncated]... != u'foo\r\n'
+ foo
- usage: prog basic [-h] {foo,bar,baz}
- prog basic: error: argument arg: invalid choice: 'foo--' (choose from 'foo', 'bar', 'baz')


======================================================================
FAIL: test_continuation (__main__.TestBashGlobal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 849, in test_continuation
    self.assertEqual(self.sh.run_command('prog basic f\t--'), 'foo\r\n')
AssertionError: u"usage: prog basic [-h] {foo,bar,baz}\r\nprog basic: error: argument arg: inval [truncated]... != u'foo\r\n'
+ foo
- usage: prog basic [-h] {foo,bar,baz}
- prog basic: error: argument arg: invalid choice: 'foo--' (choose from 'foo', 'bar', 'baz')


======================================================================
FAIL: test_quoted_exact (__main__.TestBashGlobal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 856, in test_quoted_exact
    self.assertEqual(self.sh.run_command('prog basic "f\t--'), 'foo\r\n')
AssertionError: u"usage: prog basic [-h] {foo,bar,baz}\r\nprog basic: error: argument arg: inval [truncated]... != u'foo\r\n'
+ foo
- usage: prog basic [-h] {foo,bar,baz}
- prog basic: error: argument arg: invalid choice: 'foo--' (choose from 'foo', 'bar', 'baz')


----------------------------------------------------------------------
Ran 69 tests in 43.701s

FAILED (failures=3, expected failures=8)
make: *** [test] Error 1
```

**Comment by kislyuk** [comment]
The above was on my Mac. I just tested on a RHEL based distro and everything works:
```
Linux ip-172-31-33-12 4.4.35-33.55.amzn1.x86_64 #1 SMP Tue Dec 6 20:30:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@ip-172-31-33-12 argcomplete]# cat /etc/issue
Amazon Linux AMI release 2016.09
Kernel \r on an \m

[root@ip-172-31-33-12 argcomplete]# bash --version
GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)
```

**Comment by kislyuk** [comment]
See also: https://travis-ci.org/kislyuk/argcomplete/jobs/189840642

**Comment by evanunderscore** [comment]
All the global tests are failing in the job you linked because it's using an old version of bash that doesn't support the `-D` option to `complete`. There's probably a way to tell Travis to update bash before running the tests.

**Comment by evanunderscore** [comment]
The other bash failure is also version related. The `compopt` command I used in #159 was introduced in 4.0. It's up to you whether we revert those changes, or handle both 3.x and 4.x, or just update the docs to say you need bash 4.x.

**Comment by evanunderscore** [comment]
#176 fixes the CI failure by updating bash for the OSX build job.

**Comment by evanunderscore** [comment]
@kislyuk Do you want me to merge small fixes like this straight to master, or would you prefer to review them?

**Comment by kislyuk** [comment]
@evanunderscore please use your best judgment, if the change is small but there's any possibility of the tests failing, then you can open a PR and merge it yourself; if the change is small and won't break anything, I'm fine with you merging it directly to master.

About that compopt option, is it possible to fall back on a default behavior in `scripts/register-python-argcomplete` if compopt is not available? That way we don't completely break on bash < 4.

**Comment by evanunderscore** [comment]
@kislyuk Can you confirm #177 fixes the tcsh tests on your machine?

**Comment by kislyuk** [comment]
Yes, the tcsh tests pass now. I pasted the full output in #177. Please go ahead and merge that. I'm also interested in solutions for the other failures, that you said are related to `compopt`.

**Comment by kislyuk** [comment]
Regarding the bash failures:
```
kislyuk@serenity:~/projects/argcomplete>/bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
kislyuk@serenity:~/projects/argcomplete>/usr/local/bin/bash --version
GNU bash, version 4.4.5(1)-release (x86_64-apple-darwin15.6.0)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by evanunderscore** [comment]
@kislyuk I added some extra checks in #179. Can you run the tests again and check the output?

**Comment by evanunderscore** [comment]
I believe #180 should have solved the remaining problems. I've created #181 to continue discussion about the `compopt` failure. @ignatenkobrain Please rerun the tests from master and post the output. I haven't yet tried to address any of your problems directly but I want to be sure none of them were fixed incidentally.

**Comment by kislyuk** [comment]
Yes, tests pass for me now, thanks @evanunderscore. @ignatenkobrain, please reopen if they fail for you.

**Comment by kislyuk** [comment]
Turns out tests still fail for me with these symptoms after a fresh checkout. I'm not sure what changed.

**Comment by kislyuk** [comment]
Example:
```
akislyuk@galactica:~/projects/argcomplete>./test/test.py -vvv TestBashGlobal.test_python_not_executable
test_python_not_executable (__main__.TestBashGlobal)
Test completing a script that cannot be run directly. ... FAIL

======================================================================
FAIL: test_python_not_executable (__main__.TestBashGlobal)
Test completing a script that cannot be run directly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test.py", line 1103, in test_python_not_executable
    self.assertEqual(self.sh.run_command('python ./prog basic f\t'), 'foo\r\n')
AssertionError: u"usage: prog basic [-h] {foo,bar,baz}\r\nprog basic: error: argument arg: inval [truncated]... != u'foo\r\n'
+ foo
- usage: prog basic [-h] {foo,bar,baz}
- prog basic: error: argument arg: invalid choice: 'f' (choose from 'foo', 'bar', 'baz')


----------------------------------------------------------------------
Ran 1 test in 1.083s

FAILED (failures=1)
```

**Comment by evanunderscore** [comment]
Completion didn't work for some reason. If you set `_ARC_DEBUG=1` you should be able to get some output from the global completion script.

**Comment by kislyuk** [comment]
I'm having a hard time figuring this out. It's like bash refuses to fire the `complete -D` hook at all. But the version is fine (4.4.12(1)-release).
```
akislyuk@galactica:~/projects/argcomplete>git diff
diff --git a/test/test.py b/test/test.py
index 3a66c6e..b11ccb8 100755
--- a/test/test.py
+++ b/test/test.py
@@ -1058,9 +1058,11 @@ class TestBash(_TestSh, unittest.TestCase):

     def setUp(self):
         sh = pexpect.replwrap.bash()
+        sh.child.logfile = sys.stdout
         path = ':'.join([os.path.join(BASE_DIR, 'scripts'), TEST_DIR, '$PATH'])
         sh.run_command('export PATH={0}'.format(path))
         sh.run_command('export PYTHONPATH={0}'.format(BASE_DIR))
+        sh.run_command("export _ARC_DEBUG=1")
         output = sh.run_command(self.install_cmd)
         self.assertEqual(output, '')
         self.sh = sh
```
```
akislyuk@galactica:~/projects/argcomplete>./test/test.py -vvv TestBashGlobal.test_python_not_executable
test_python_not_executable (__main__.TestBashGlobal)
Test completing a script that cannot be run directly. ... export PATH=/Users/akislyuk/projects/argcomplete/scripts:/Users/akislyuk/projects/argcomplete/test:$PATH
[PEXPECT_PROMPT>export PYTHONPATH=/Users/akislyuk/projects/argcomplete
[PEXPECT_PROMPT>export _ARC_DEBUG=1
[PEXPECT_PROMPT>eval "$(activate-global-python-argcomplete --dest=-)"
[PEXPECT_PROMPT>cd /Users/akislyuk/projects/argcomplete/test_dir_pyVOC3JO
[PEXPECT_PROMPT>chmod -x ./prog
[PEXPECT_PROMPT>./prog
bash: ./prog: Permission denied
[PEXPECT_PROMPT>python ./prog basic f
usage: prog basic [-h] {foo,bar,baz}
prog basic: error: argument arg: invalid choice: 'f' (choose from 'foo', 'bar', 'baz')
[PEXPECT_PROMPT>FAIL
exit
exit

======================================================================
FAIL: test_python_not_executable (__main__.TestBashGlobal)
Test completing a script that cannot be run directly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test.py", line 1105, in test_python_not_executable
    self.assertEqual(self.sh.run_command('python ./prog basic f\t'), 'foo\r\n')
AssertionError: u"usage: prog basic [-h] {foo,bar,baz}\r\nprog basic: error: argument arg: inval [truncated]... != u'foo\r\n'
+ foo
- usage: prog basic [-h] {foo,bar,baz}
- prog basic: error: argument arg: invalid choice: 'f' (choose from 'foo', 'bar', 'baz')


----------------------------------------------------------------------
Ran 1 test in 1.179s

FAILED (failures=1)
```

**Comment by evanunderscore** [comment]
That does look odd. You can try printing a message at the beginning of `_python_argcomplete_run` in `python-argcomplete.sh` to check whether it's even getting that far.

If I had to guess I'd say you're somehow running the old global completion script, but I'm not sure how that could be happening since the new one should be overriding it in the test setup.

**Comment by kislyuk** [comment]
OK I found the culprit. The global completion conflicts with the
bash-completion Python completion module. Fix incoming.

**Comment by kislyuk** [comment]
Fixed in https://github.com/kislyuk/argcomplete/commit/ea3290e2fb153da84270f557878fcded9467c4ec

**Comment by evanunderscore** [comment]
Oh, that makes sense. Glad you resolved it.
